### ISSUE TITLE
Request for running Firestore emulator in cloud build

### ISSUE THREAD

**Issue by blainegarrett** [Timtech4u/awesome-cloudbuild#1]
We've been having a heck of a time trying to get the Firestore emulator running in the cloud to run our integration tests for CI/CD using google cloud build. We've tried just about everything and there isn't much information on the web. If there is a solution, I'd love to know. It would be a huge asset to the list.

**Comment by Timtech4u** [comment]
Hi @blainegarrett , I was wondering if you could make use of the **npm** builder to install **firebase-emulator** globally on your workspace then run your tests?

Installation for Firebase Emulator: https://firebase.google.com/docs/rules/emulator-setup
NPM Cloud Builder: https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/npm

I would be super happy to help test this approach out.
