### ISSUE TITLE
 Start the service CMD ["npm"  "start"] missing in vue dockerfile [question]

### ISSUE THREAD

**Issue by LOG-TAG** [Timtech4u/awesome-cloudbuild#2]
I believe to Start the service CMD npm start needed ?  it will call package.json "start": "npm run dev",    Is that correct or CMD [ "http-server", "dist" ] enough for serving index.html via http server in index.js in root (https://cloud.google.com/run/docs/quickstarts/build-and-deploy)

**Comment by Timtech4u** [comment]
Hi @LOG-TAG , thanks for this.
CMD [ "http-server", "dist" ] is enough as it serves the build from "npm run build" which exists in "dist" folder.

**Comment by LOG-TAG** [comment]
thanks for responding, need some help

1>if we are using https://github.com/webpack/webpack-dev-middleware in vuejs project, then in index.js we should use https://github.com/webpack/webpack-dev-middleware for serving  index.html via express?

(https://github.com/suprithasraoa/vue-deploy/blob/537ff1f381a82e47c89274e28c341f8109eb4e78/package.json)  

something like this
```
const express = require('express');
const path = require('path');
const app = express();
const historyApiFallback = require('connect-history-api-fallback');

if (process.env.NODE_ENV !== 'production') {
    const webpackMiddleware = require('webpack-dev-middleware');
    const webpack = require('webpack');
    const webpackConfig = require('./webpack.config.js');
    const webpackInstance = webpackMiddleware(webpack(webpackConfig));
    app.use(webpackInstance);
    app.use(historyApiFallback);
    app.use(webpackInstance);
} else {
    app.use(express.static('dist'));
    app.get('*', (req, res) => {
        res.sendFile(path.join(__dirname, 'dist/index.html'));
    })
}

app.listen(process.env.PORT || 3050, () => console.log('Listening...'));

```
it's the right way to it?  __dirname, 'dist/index.html'  may cause this error

Error: Forbidden
Your client does not have permission to get URL / from this server.

(I'm not using  Cloud Build, so there is need of Granting IAM Permissions right? I'm using gcloud commands IAM is not needed I assume!) it's a   publicPath. error ? ./ vs /



2> if we get express js config I'm assuming I can do this ExpressJS and NodeJS, configure the caching behavior using the Cache-Control header like so:

 res.set('Cache-Control', 'public, max-age=300, s-maxage=600');  (https://firebase.googleblog.com/2019/04/firebase-hosting-and-cloud-run.html) index.js we have put htis right?
